# Generated by Django 6.0 on 2025-12-23 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number. It can start with '+', followed by 7‑15 digits.",
                        regex="^\\+?[0-9]{7,15}$",
                    )
                ],
            ),
        ),
    ]
