# Generated by Django 5.2.9 on 2026-01-07 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number. It can start with '+', followed by 7-15 digits.", regex='^\\+?[0-9]{7,15}$')]),
        ),
    ]
