# Generated by Django 6.0 on 2025-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer", models.CharField(max_length=100, null=True)),
                ("seller", models.CharField(max_length=100, null=True)),
                ("transaction_date", models.DateField(auto_now=True)),
                ("status", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
