# Generated by Django 6.0 on 2025-12-25 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_item_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
